image: Ubuntu

init:
  - sudo sed -i 's!/var/lib/mysql!/dev/shm/mysql!' /etc/mysql/mysql.conf.d/mysqld.cnf
  - sudo sed -i 's!/var/lib/mysql!/dev/shm/mysql!' /etc/apparmor.d/usr.sbin.mysqld
  - sudo apparmor_parser -r /etc/apparmor.d/usr.sbin.mysqld
  - sudo cp -rp /var/lib/mysql /dev/shm
  - sudo mv /var/lib/mysql /var/lib/mysql.local

services:
  - mysql

build:
  project: Skoruba.IdentityServer4.Admin.sln
  verbosity: minimal

version: '1.0.{build}'
